name: flutter_playground
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.6.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  mono_kit:
  intl:
  provider:
  flutter_hooks:
  tinycolor:
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono:
flutter:
  uses-material-design: true
  assets:
    - assets/images/
